#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
    CREATE USER $QUESTION_DB_USER WITH PASSWORD '$QUESTION_DB_PASSWORD';
    CREATE DATABASE $QUESTION_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $QUESTION_DB_USER TO $QUESTION_DB_USER;
    CREATE DATABASE $QUESTION_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $QUESTION_DB_NAME TO $QUESTION_DB_USER;
EOSQL